### ISSUE TITLE
Optional: Typedef step breaks application

### ISSUE THREAD

**Issue by ayyrk27** [Janamou/firebase-counter-steps#5]
The codelab "Build an AngularDart & Firebase Web App" worked for me.  I quickly followed the steps and the app worked exactly like the tutorial.

Until I tried adding the typedef T UpdateFunction<T>(T value);

At that point the app no longer ran.  I did some digging into typdef. Tried adding a very simple typdef, etc.. Just adding a typdef seems to what breaks things.

I attached a screen shot of the error.

![typdef](https://user-images.githubusercontent.com/1774421/30124752-2ccad6ac-9304-11e7-98d5-f6f9e9081376.PNG)

**Comment by kwalrath** [comment]
@ayyrk27: Thanks very much for this report! Are you using the 1.24 SDK and Angular 4? (These are the defaults if you created the project last Friday or later, I believe.) 

@Janamou: It sounds like this might be an incompatibility with Angular or the new SDK. I wonder if we could/should use the new function type syntax introduced in Dart 1.24. More info: https://www.dartlang.org/guides/language/language-tour#typedefs (scroll down to the "New function type syntax" note) or https://github.com/dart-lang/sdk/blob/master/docs/language/informal/generic-function-type-alias.md.

/cc @filiph

**Comment by matanlurey** [comment]
Unfortunately it's impossible for me to debug this without a Dart SDK/Angular version.

**Comment by kwalrath** [comment]
@ayyrk27 could you please give us:

1. the output of `dart --version` (for whatever copy you're using)
2. your pubspec.yaml and pubspec.lock files
3. if it's easy, maybe a diff between your code and either https://github.com/Janamou/firebase-counter-steps/tree/master/4-loaddatafromfirebase/firebase_counter or https://github.com/Janamou/firebase-counter-steps/tree/master/5-likedislike/firebase_counter 

For the record, the instructions for adding the typedef are in the [codelab](https://codelabs.developers.google.com/codelabs/angulardart-firebase-web-app/), in [step 11's](https://codelabs.developers.google.com/codelabs/angulardart-firebase-web-app/#10) "Optional: Typedef" section.

Since the typedef is optional, this isn't a top-priority bug (unless it's an Angular/SDK bug), but I'd still like to update the tutorial with the fix/workaround/faq.

**Comment by Janamou** [comment]
@ayyrk27 Thank you for the report and I am sorry for that. It should be fixed with the latest update of this codelab: https://github.com/Janamou/firebase-counter-steps/pull/7

@kwalrath Was probably because of the incompatibility, it works now after the update :-)
